# 
# NBR 5410 Calculator
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



[tool.pyright]
typeCheckingMode = 'strict'
stubPath = 'src/typings/'
ignore = [ 'src/typings/', 'src/UiMainWindow.py' ]
reportUnnecessaryTypeIgnoreComment = true



[tool.pylint]
	[tool.pylint.main]
	init-hook = 'import sys; sys.path.append( "deployment/env/lib/python3.10/site-packages" )'
	ignore-paths = [ '.*/src/typings/.*', '.*/src/UiMainWindow.py' ]
	
	[tool.pylint.format]
	indent-string = '	'
	good-names = [ '_', 'x', 'y', 'i', 'j', 'k', 'id' ]
	
	
	[tool.pylint.'messages control']
	disable = [
		'fixme',
		'trailing-whitespace',
		'missing-final-newline',
		'logging-fstring-interpolation',
		'too-many-instance-attributes',
		'unspecified-encoding',
		'no-name-in-module',	# Fix PyLint bug?
	]
	
	
	[tool.pylint.basic]
	module-naming-style = 'camelCase'
	const-naming-style = 'UPPER_CASE'
	
	function-naming-style = 'camelCase'
	argument-naming-style = 'camelCase'
	variable-naming-style = 'camelCase'
	inlinevar-naming-style = 'camelCase'
	
	class-naming-style = 'PascalCase'
	class-const-naming-style = 'UPPER_CASE'
	class-attribute-naming-style = 'camelCase'
	method-naming-style = 'camelCase'
	attr-naming-style = 'camelCase'